# Generated by hand for TanPit：浸液酸碱记录加「作废」标记

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pits", "0001_initial")]
    operations = [
        migrations.AddField(
            model_name="liquorsample",
            name="voided",
            field=models.BooleanField(default=False),
        ),
    ]
